from typing import Any, Protocol

class ReadRepository(Protocol):
	async def get_by_id(self, user_id: int) -> Any:...
	async def get_all(self) -> list[Any]: ...

class WriteRepository(Protocol):
	async def add(self, data: Any) -> None: ...

class FullRepository(ReadRepository, WriteRepository, Protocol):
	async def update(self, data: Any) -> None: ...
	async def delete(self, data: Any) -> None: ...