from typing import Any, Protocol

class FullRepository(Protocol):
	async def put(self, key: Any, value: Any) -> None: ...
	
	async def get(self, key: Any) -> Any: ...
	
	async def delete(self, key: Any) -> None: ...